### PR TITLE
To support using shapely object to manipulate database geometry data.

### PR DESCRIPTION
**Pull request by wuwwen**
@ryan-kipawa I just modified the notebook to add some example of shapely object usage. If the testing needed to be added for testpy, then the action of build should also be modified. Please let me know your opinion.

### CODE REVIEW

**Comment by wuwwen** [comment]
@ryan-kipawa There is build error. Please check the detail. The typing caused this failure. How to fix it?

image

**Comment by ryan-kipawa** [comment]
I think we should use ruff's nice suggestion here of `importlib.util.findspec`:

https://docs.astral.sh/ruff/rules/unused-import/

With this we could remove the import of _shapely_ all together, as well as the try_import method. Findspec essentially accomplished the same thing.

**Comment by wuwwen** [comment]
I haven't used the importlib.util.findspec, the test always fail says that he model has not to_wkt property. sys.modules.get works well. The import process has been removed. Please review it again. @ryan-kipawa

**Review by ryan-kipawa — COMMENTED** [review]
Okay, now that the import has been removed, could we add a test.

**Comment by wuwwen** [comment]
@ryan-kipawa Test for shapely geometry has been added.

**Review by ryan-kipawa — APPROVED** [review]
Looks good, thanks @wuwwen

**Pull request merged**
